DIPParams:
  n_iter: 30000
  lr: 0.001

  pretr_iter: 1000

  in_channels: 1
  out_channels: 1
  nscale: 3
  up_down_channels: 128
  skip_channels: 4
  pad: "reflection"
  upsample_mode: "trilinear"

  filter_size_down: 3
  filter_size_up: 3
  filter_size_skip: 1

IterParams:
  n_iter: 5000
  mu: 0.001
  lr: 0.005
  flag: 0

NFParams:
  n_iter: 100000
  lr: 0.0001

  n_layers: 10
  hidden_size: 208
  use_pe: True

ImgModelParams:
  apa_size: 25
  xy_res: 0.92
  z_res: 1.0
  NA: 0.75
  layers: 11
