DIPParams:
  n_iter: 30000
  lr: 0.001

  # Constant value fitting duration
  pretr_iter: 500

  # Network parameters (unchanged)
  in_channels: 1
  out_channels: 1
  nscale: 3
  up_down_channels: 128
  skip_channels: 4
  pad: "reflection"
  upsample_mode: "trilinear"
  filter_size_down: 3
  filter_size_up: 3
  filter_size_skip: 1

IterParams:
  n_iter: 5000
  mu: 0.001
  lr: 0.005
  flag: 0

HQSParams:
  n_iter: 80
  lr: 0.001
  flag: 0

ImgModelParams:
  apa_size: 25
  xy_res: 0.92
  z_res: 1.0
  NA: 0.75
  layers: 11

DenoiserParams:
  gain: 0.2
  shape: 0.13
  color_bias: 0.0
  sigma_tl: 0.005
  sigma_r: 0.003